[general]
use_wandb = 1
seed = 0
style = 'unet'
d_adapter = 1024
val_size = 1024
normalize_embeddings = true
depth = 3
embs = ['dpr', 'gte']
lm_base_name = "google-bert/bert-base-uncased"
upscale_num = 16
n_embs_per_batch = 2
max_seq_length = 512

[train]
src_emb = 'dpr'
tgt_emb = 'gte'
lr = 1e-4
bs = 256
save_every = 6_000
epochs = 50
val_bs = 64
dataset = "nq"
max_grad_norm = 10.0
gradient_accumulation_steps = 2
loss_coefficent_rec = 0
loss_coefficient_trans = 1
loss_coefficient_vsp = 0
loss_coefficient_cc = 0
add_noise = 0
add_noise_rotation = 0
force_dump = true
overwrite = true

[logging]
wandb_project = 'edx-v1-baselines-nq'
wandb_name = 'edx-v1-baselines-nq'
save_dir = '/share/shmatikov/rishi/edx/baselines/{}/'
