[general]
use_wandb = 1
seed = 0
style = 'unet'
d_adapter = 512
d_hidden = 1024
normalize_embeddings = true
depth = 3
transform_depth = 4
# embs = [ "gte", "gtr", "stella", "sentence-t5", "e5", "snowflake", "ember", "sbert", "gist", "clip", "bert-nli",]
lm_base_name = "google-bert/bert-base-uncased"
upscale_num = 16
n_embs_per_batch = 1
max_seq_length = 512
mixed_precision = 'bf16'
val_size = 4096

[train]
unsup_emb = 'gte'
sup_emb = 'gtr'
lr = 1e-4
bs = 512
save_every = 6_000
epochs = 10
val_bs = 256
dataset = "nq"
max_grad_norm = 10.0
gradient_accumulation_steps = 2
loss_coefficient_rec = 0.5
loss_coefficient_vsp = 1.0
loss_coefficient_cc_trans = 1
loss_coefficient_cc_rec = 10
loss_coefficient_gen = 0.5
loss_coefficient_disc = 0.1
add_noise = 0
add_noise_rotation = 0
force_dump = true
overwrite = false
freeze_params = false
patience = 25
delta = 0.0
use_small_output_adapters = false
use_residual_adapters = true
no_scheduler = true
top_k_size = 128
heatmap_size = 16
k = 16
finetune_mode = false
gan_style = "vanilla"

[logging]
wandb_project = 'unsupervised_disc'
wandb_name = 'unsupervised'
load_dir = './finetuning_unsupervised/n:100000,e:10,s:n_double,d:4,d:4,d:64/'
save_dir = './finetuning_unsupervised/{}/'


[discriminator]
smooth = 0.9
disc_dim = 1024
disc_depth = 3
disc_lr = 1e-4
eps = 6.25e-10
use_residual = true
